### PR TITLE
Sample Exam Questions and Answers generation

### LINKED ISSUE #68: Sample exams template research
Elaborate on possibilities to tweak current syllabus template in order to support generation of Sample Exam documents. Namely:

- Sample Questions (https://istqb-main-web-prod.s3.amazonaws.com/media/documents/ISTQB_CTFL_Sample-Exam-Questions_v4.0.pdf)
- Sample Answers (https://istqb-main-web-prod.s3.amazonaws.com/media/documents/ISTQB_CTFL_Sample-Exam-Answers_v4.0.pdf)
- Exam Structure and Rules (https://istqb-main-web-prod.s3.amazonaws.com/media/documents/ISTQB_Exam-Structure-Tables_v1_6.pdf)

Beware, we are not trying to generate documents which are identical to the existing ones. We should research possible formatting of questions (stem, question, answers options, justification, answer key) in Markdown to generate documents which has the same core as syllabus just a different content.

Possibly we could generate Exam document (stem, question, answers options), Exam with Answers document (stem, question, answers options, justification, answer key).

Exam Structure and Rules document should be split by chapters, but I am not sure if it makes sense to convert such table into Markdown.

### PR DESCRIPTION
**Pull request by Witiko**
Closes #68 and #85.

### Tasks

- [x] Update the structure of the repository.
- [x] Add code for typesetting sample exam questions.
- [x] Add code for typesetting sample exam answers.
  - [x] Typeset answer key.
  - [x] Typeset answers.
- [x] Validate files `metadata.yml` and `questions.yml` in CI.

### CODE REVIEW

**Comment by Witiko** [comment]
The first commit de88e91:

- Adds the `sample-exam-questions.tex` document with a draft of an example ISTQB sample exam questions document.
- Separates the markdown theme `istqb/syllabus` into the following markdown themes:
  - `istqb/common` -- Common code for different types of ISTQB documents. Currently just a copy of `istqb/syllabus`.
  - `istqb/syllabus` and `istqb/body-of-knowledge` -- Code for ISTQB syllabus and body of knowledge documents. Currently mostly empty with all functionality imported from `istqb/common`.
  - `istqb/sample-exam` -- Code for ISTQB sample exam questions and answers documents. Currently adds support for a new metadata field `compatibility` for specifying the compatibility of sample exam documents with syllabus documents.
  - `istqb/sample-exam/questions` -- Code for ISTQB sample exam questions documents. Currently adds the text " -- Questions" after the text of the `type` metadata field on the landing page and in headers.
  - `istqb/sample-exam/answers` -- Code for ISTQB sample exam questions documents. Currently adds the text " -- Questions" after the text of the `type` metadata field on the landing page and in headers.

The pull request is currently set to merge into PR #82, because the code is based on the code from branch `fix/md-content-updates`. After #82 has been merged into branch `main`, I will rebase this PR onto branch `main` and set this PR to merge into branch `main`.

**Review by danopolan — DISMISSED** [review]

**Comment by Witiko** [comment]
After commit 2aafbae from this PR, the data processing code is almost complete. To show this, the document `sample-exam-questions.tex` reads the file `sample-exam-md/metadata.yml` and prints a summary of its contents:

image

The next step will be finishing the data processing code and typesetting the questions in accordance with the acceptance criteria from #85.

**Comment by Witiko** [comment]
@danopolan: In commit 9387abf from this PR, I added implemented the typesetting of sample exam questions. I will appreciate your review of the resulting document [`sample-exam-questions.pdf`][2] at your convenience.

As discussed in https://github.com/danopolan/istqb_latex/issues/85#issuecomment-1755789580, I reused the layout of syllabus and body of knowledge documents instead of trying to exactly reproduce the layout of [`ISTQB_CTFL_Sample-Exam-Questions_v4.0.pdf`][1].

I also identified an issue with parsing questions that contain fancy lists that use roman numerals for item labels:
``` yml
question: |
  Which of the following factors (i-v) have SIGNIFICANT influence on the test process?

  i. The SDLC
  ii. The number of defects detected in previous projects
  iii. The identified product risks
  iv. New regulatory requirements forcing
  v. The number of certified testers in the organization
```
image

This issue is being monitored in https://github.com/Witiko/markdown/issues/359. A part-time contributor affiliated with the Markdown package has committed to resolving it by the end of this month. The resolution cost will be accommodated within the Markdown project's budget, ensuring no financial implications for ISTQB.

 [1]: https://istqb-main-web-prod.s3.amazonaws.com/media/documents/ISTQB_CTFL_Sample-Exam-Questions_v4.0.pdf
 [2]: https://github.com/danopolan/istqb_latex/suites/17290078354/artifacts/987813768

**Review by danopolan — COMMENTED** [review]
I have checked the generated PDF with questions and there are few issues to be addressed:

1. Lists in the question stem should be indented (two indents)
2. List of answer options should be indented (one indent)
3. Level should not be defined for ATLaS (fixed recently for other documents)
4. Markdown issues with Roman numbered lists could be accommodated by ISTQB budget. We are happy to support the Markdown project with this contribution.

**Comment by Witiko** [comment]
> 1. Lists in the question stem should be indented (two indents)
> 2. List of answer options should be indented (one indent)
> 3. Level should not be defined for ATLaS (fixed recently for other documents)

I fixed these issues in commit f74ec58 from this PR.

> 4. Markdown issues with Roman numbered lists could be accommodated by ISTQB budget.
> We are happy to support the Markdown project with this contribution.

I appreciate that. Can I acknowledge ISTQB's support in https://github.com/witiko/markdown#acknowledgements?

**Comment by danopolan** [comment]
> I fixed these issues in commit https://github.com/danopolan/istqb_latex/commit/f74ec587a010c45df4fb336e9ddd12656ca9bf1e from this PR.

Despite this is according to the Template when I see it, it doesn't look good. So I propose removing the indent for answer options and keeping only one for lists in the question stem. Sorry for the changes.

> I appreciate that. Can I acknowledge ISTQB's support in https://github.com/witiko/markdown#acknowledgements?

Sure, thx.

**Comment by Witiko** [comment]
@danopolan: In commits 15540f6..61e383d from this PR, I implemented the typesetting of sample exam answers. I will appreciate your review of the resulting document [sample-exam-answers.pdf](https://github.com/danopolan/istqb_latex/suites/17446952188/artifacts/997168323) at your convenience.

**Review by danopolan — APPROVED** [review]
Looks really good. I did not spot any error in the PDF or in the code. So it's good to go.

**Comment by Witiko** [comment]
Excellent. Over the weekend, I will release Markdown 3.2.0, which will fix the issues with Roman numbered lists. Then, I will update the CI to use Markdown 3.2.0 and merge this PR.

**Pull request merged**
